---
- name: remove docker-ce
  yum:
    name: docker-ce
    state: absent

- service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  with_items:
    - NetworkManager
    - firewalld

- yum:
    name: "centos-release-openstack-{{ openstack_release }}"
    state: present

- template:
    dest: "/etc/yum.repos.d/{{ item }}"
    src: "yum.repos.d/{{ item }}.j2"
  loop:
    - CentOS-Ceph-Luminous.repo
    - CentOS-OpenStack-queens.repo
  when: openstack_release == "queens"

- yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
    disablerepo: "epel"
  with_items:
    - openstack-utils
    - puppet

- yum:
    name: open-vm-tools
    state: present
  when: ansible_product_name == "VMware Virtual Platform"

- replace:
    dest: /etc/selinux/config
    regexp: SELINUX=enforcing
    replace: SELINUX=disabled
    backup: yes

#- lineinfile:
#    dest: /root/.bashrc
#    line: "{{ item }}"
#  with_items:
#    - alias cont='ssh root@192.168.61.11'
#    - alias com1='ssh root@192.168.61.21'
#    - alias com2='ssh root@192.168.61.22'
#    - alias com3='ssh root@192.168.61.23'
#    - alias opsconf="grep -v '^$\|^\s*\#' "
#    - source ~/keystonerc_admin

- user:
    name: sysop
    groups: wheel
    append: yes
    shell: /bin/bash
    createhome: yes

- template:
    src: centos/openrc_sysop.j2
    dest: /home/sysop/openrc

- lineinfile:
    dest: /home/sysop/.bashrc
    line: "source openrc"

- template:
    src: centos/stack.j2
    dest: /etc/sudoers.d/stack
