---

- name: preparing node of packstack
  hosts: "{{ host_group | default('openstack') }}"
  become: yes
  roles:
    - centos-common
#    - centos-preparing-for-packstack
  tags:
    - openstack

- name: preparing instances of kubernetes
  hosts: "{{ host_group | default('instances') }}"
  become: yes
  roles:
    - centos-preparing-for-instances
  tags:
    - instances

- name: install netdata to OpenStack nodes
  hosts: "{{ host_group | default('openstack') }}"
  become: yes
  roles:
    - centos-netdata
  tags:
    - netdata
